### ISSUE TITLE
scale animation BUG

### ISSUE THREAD

**Issue by Luncher** [flyover/spriter.js#3]
Hi man, thank you for the open source, I recently test your code using an example of a problem emerged:
In the spine animation software inside scale change of direction for the Y direction, the bottom of the center position unchanged. But after tests found code is x direction changed.
Test data here:
![pumpkin](https://cloud.githubusercontent.com/assets/5138977/10928512/21c8aa5e-82e4-11e5-8a35-b7709fb87a52.png)

atlas data:

Pumpkin.png
size: 512,256
format: RGBA8888
filter: Linear,Linear
repeat: none
nangua1
  rotate: false
  xy: 2, 2
  size: 480, 161
  orig: 480, 161
  offset: 0, 0
  index: -1

---

json data:

{
"skeleton": { "hash": "OmYbVfijIL05mUwvc6eDJcqaP+A", "spine": "2.1.27", "width": 479.99, "height": 160.99, "images": "./images/" },
"bones": [
	{ "name": "root" },
	{ "name": "nangua1", "parent": "root", "length": 107.98, "x": 3.79, "y": 8.28, "rotation": 89.09 }
],
"slots": [
	{ "name": "nangua1", "bone": "nangua1", "attachment": "nangua1" }
],
"skins": {
	"default": {
		"nangua1": {
			"nangua1": { "x": 72.14, "y": 4.94, "rotation": -89.09, "width": 480, "height": 161 }
		}
	}
},
"animations": {
	"animation": {
		"slots": {
			"nangua1": {
				"attachment": [
					{ "time": 0, "name": "nangua1" }
				]
			}
		},
		"bones": {
			"nangua1": {
				"rotate": [
					{ "time": 0, "angle": 0, "curve": "stepped" },
					{ "time": 0.5, "angle": 0, "curve": "stepped" },
					{ "time": 1, "angle": 0, "curve": "stepped" },
					{ "time": 1.5, "angle": 0, "curve": "stepped" },
					{ "time": 2, "angle": 0, "curve": "stepped" },
					{ "time": 2.5, "angle": 0, "curve": "stepped" },
					{ "time": 3, "angle": 0 }
				],
				"translate": [
					{ "time": 0, "x": 0, "y": 0, "curve": "stepped" },
					{ "time": 0.5, "x": 0, "y": 0, "curve": "stepped" },
					{ "time": 1, "x": 0, "y": 0, "curve": "stepped" },
					{ "time": 1.5, "x": 0, "y": 0, "curve": "stepped" },
					{ "time": 2, "x": 0, "y": 0, "curve": "stepped" },
					{ "time": 2.5, "x": 0, "y": 0, "curve": "stepped" },
					{ "time": 3, "x": 0, "y": 0 }
				],
				"scale": [
					{ "time": 0, "x": 1, "y": 1 },
					{ "time": 0.5, "x": 1.113, "y": 1 },
					{ "time": 1, "x": 1, "y": 1 },
					{ "time": 1.5, "x": 1.113, "y": 1 },
					{ "time": 2, "x": 1, "y": 1 },
					{ "time": 2.5, "x": 1.113, "y": 1 },
					{ "time": 3, "x": 1, "y": 1 }
				]
			},
			"root": {
				"rotate": [
					{ "time": 0, "angle": 0, "curve": "stepped" },
					{ "time": 3, "angle": 0 }
				],
				"translate": [
					{ "time": 0, "x": 0, "y": 0, "curve": "stepped" },
					{ "time": 3, "x": 0, "y": 0 }
				],
				"scale": [
					{ "time": 0, "x": 1, "y": 1, "curve": "stepped" },
					{ "time": 3, "x": 1, "y": 1 }
				]
			}
		},
		"drawOrder": [
			{ "time": 0 }
		]
	}
}
}

---

Waiting for your reply :+1:

**Comment by flyover** [comment]
I've submitted a fix for this to the spine.js repository.

https://github.com/flyover/spine.js/commit/2dd683d45cff59c51cbc42d3ec7fb560be3c570d
