### ISSUE TITLE
Sprite objects not loaded if they are children of bones

### ISSUE THREAD

**Issue by Heishe** [flyover/spriter.js#5]
I used to load used sprite objects in an animation from the obj_info_keys/obj_info_map and do game logic dependent stuff with the animation depending on the names of the objects. This worked fine, the obj_info_map would have a mixture of bones and sprite objects and I could iterate it (and basically discard the bones). More importantly, it would contain all sprite objects used by any of an entities animations (basically a union of the sets) which was a pretty awesome property.

However it appears in some cases the obj_info_map does not have any sprite objects at all (only bones). I'm not sure how to reliably reproduce this (I could upload the project somewhere), but I can say that all sprite objects in our animations are now children of bones - there are no "free floating" sprites in Spriter so to speak.

Is this intentional? How else can I get the set of all used sprite objects?

**Comment by Heishe** [comment]
Just now I see that the sprite objects are not even in the raw obj_info of the .scon which is exported by Spriter... so its probably an issue or something I don't understand how the file format is exported from Spriter.

**Comment by pixelpicosean** [comment]
Did you use the correct scon export settings which are located in File->Other File Actions...->Custom Save Options? You can specific some obj_info related settings here and try again.

**Comment by Heishe** [comment]
Yeah, the option to export sprite objects was enabled but they weren't. Seems this was a bug, because upgrading to the latest release seems to have fixed it!
